title: Etki Acilan
url: "https://etkiacilan.github.io/"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://etkiacilan.github.io/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
